{{- if .Values.database.enabled -}}

{{- $fullName := include "zbi-mongodb.fullname" . -}}

apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{$fullName}}
  labels:
    {{- include "zbi-mongodb.labels" . | nindent 4 }}
spec:
  members: {{.Values.database.members}}
  type: {{.Values.database.architecture}}
  version: {{.Values.database.version}}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: {{$fullName}}-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin
    - name: zbi
      db: zbiRepo
      passwordSecretRef:
        name: {{$fullName}}-repo-password
      roles:
        - name: readWrite
          db: zbiRepo
      scramCredentialsSecretName: zbi
additionalMongodConfig:
  storage.wiredTiger.engineConfig.journalCompressor: zlib
statefulset:
  spec:
    template:
      spec:
        containers:
          - name: mongod
            resources:
              limits:
                cpu: {{.Values.database.resources.limits.cpu}}
                memory: {{.Values.database.resources.limits.memory}}
              resources:
                cpu: {{.Values.database.resources.requests.cpu}}
                memory: {{.Values.database.resources.requests.memory}}
            affinity:
              podAntiAffinity:
                requireDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - zbi-mongodb
                    topologyKey: "kubernetes.io/hostname"
    volumeClaimTemplates:
      - metadata:
          name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: {{.Values.database.persistence.storageClassName}}
            resources:
              requests:
                storage: {{.Values.database.persistence.storageSize}}
{{- end}}