{{- if .Values.database.enabled}}

{{- $fullName := include "zbi-mongodb.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{$fullName}}-admin-password
  labels:
    {{- include "zbi-mongodb.labels" . | nindent 4 }}
data:
  {{- $adminSecretObj := (lookup "v1" "Secret" .Release.Namespace "($fullName)-admin-password") | default dict }}
  {{- $adminSecretData := (get $adminSecretObj "data") | default dict}}
  {{- $adminPassword := (get $adminSecretData "password") | default (randAlphaNum 16 | b64enc)}}

  password: {{$adminPassword}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$fullName}}-repo-password
  labels:
    {{- include "zbi-mongodb.labels" . | nindent 4 }}
data:
  {{- $zbiSecretObj := (lookup "v1" "Secret" .Release.Namespace "($fullName)-repo-password") | default dict }}
  {{- $zbiSecretData := (get $zbiSecretObj "data") | default dict}}
  {{- $zbiPassword := (get $zbiSecretData "password") | default (randAlphaNum 16 | b64enc)}}

  password: {{$zbiPassword}}
{{- end}}