{{- $fullName := include "zbi-control-plane.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{$fullName}}-secret
  labels:
    {{- include "zbi-control-plane.labels" . | nindent 4 }}
data:
  {{- $accessTokenPrivateKey := .Values.jwtKeys.accessToken.private | b64enc }}
  {{- $accessTokenPublicKey := .Values.jwtKeys.accessToken.public | b64enc }}
  {{- $refreshTokenPrivateKey := .Values.jwtKeys.refreshToken.private | b64enc }}
  {{- $refreshTokenPublicKey := .Values.jwtKeys.refreshToken.public | b64enc }}
  ACCESS_TOKEN_PRIVATE_KEY: {{ .Values.jwtKeys.accessToken.private | b64enc  }}
  ACCESS_TOKEN_PUBLIC_KEY: {{$accessTokenPublicKey}}
  REFRESH_TOKEN_PRIVATE_KEY: {{$refreshTokenPrivateKey}}
  REFRESH_TOKEN_PUBLIC_KEY: {{$refreshTokenPublicKey}}
{{- if .Values.database.create}}
{{- $databaseName := include "zbi-control-plane.databasename" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$databaseName}}-admin-password
  labels:
    {{- include "zbi-control-plane.labels" . | nindent 4 }}
data:
  {{- $secretName := printf "%s-admin-password" (include "zbi-control-plane.databasename" .) }}
  {{- $adminSecretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $adminSecretData := (get $adminSecretObj "data") | default dict}}
  {{- $adminPassword := (get $adminSecretData "password") | default (randAlphaNum 16 ) | b64enc}}
  password: {{$adminPassword}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{$databaseName}}-repo-password
  labels:
    {{- include "zbi-control-plane.labels" . | nindent 4 }}
data:
  {{- $secretName := printf "%s-repo-password" (include "zbi-control-plane.databasename" .) }}
  {{- $zbiSecretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $zbiSecretData := (get $zbiSecretObj "data") | default dict}}
  {{- $zbiPassword := (get $zbiSecretData "password") | default (randAlphaNum 16 ) | b64enc }}
  password: {{$zbiPassword}}
{{- end}}