export default {
    port: 4000,
    database: ``,
    redis: ``,
    dbUri: "mongodb://localhost:27017/zbiRepo",
    createAdmin: ``,
    adminEmail: ``,
    adminPassword: ``,
    saltWorkFactor: 10,
    accesstokenTtl: "15m",
    refreshtokenTtl: "1y",
    accessTokenPrivateKey: ``,
    accessTokenPublicKey: ``,
    refreshTokenPrivateKey: ``,
    refreshTokenPublicKey: ``,
    googleTokenEndpoint: ``,
    googleClientId: ``,
    googleClientSecret: ``,
    googleOauthRedirectUrl: ``   
}